spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/myweb?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowMultiQueries=true
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/myweb?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowMultiQueries=true
    username: root
    password: root
#    url: jdbc:mysql://172.30.154.61:3306/platform_gdgj?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowMultiQueries=true
#    username: root
#    password: rzxNS_123

logging:
  level:
    root: warn
    com.sm.mp.dao: trace
  pattern:
    console: '%p%m%n'

#mybatis-plus:
#  mapper-locations:
#    -: mapper/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#mybatis-plus:
#  mapper-locations:
#    classpath*: mapper/*.xml

#逻辑删除标识
mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
#    sql-parser-cache: true